version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/magazinelectronice
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=rootpassword
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "magazinelectronice"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
